# Generated by Django 4.1 on 2022-08-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_extrauser'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='token',
            name='verified_date',
            field=models.DateTimeField(null=True, verbose_name='Дата и время подтверждения адреса'),
        ),
        migrations.DeleteModel(
            name='ExtraUser',
        ),
    ]
