# Generated by Django 4.1 on 2022-08-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_token_email_verified_token_verified_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='sendmail_date',
            field=models.DateTimeField(null=True, verbose_name='Дата и время последней отправки письма подтверждения'),
        ),
    ]
