# Generated by Django 4.1.2 on 2022-11-28 10:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_token_sendmail_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='settings',
            unique_together={('user',)},
        ),
    ]
