# Generated by Django 4.2.3 on 2023-08-01 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название мероприятия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('start_time', models.DateTimeField(verbose_name='Дата начала мероприятия')),
                ('end_time', models.DateTimeField(verbose_name='Дата окончание мероприятия')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REGISTERED', 'Зарегистрирован'), ('VISITED', 'На мероприятии'), ('REFUSED', 'Отмена регистрации')], max_length=15)),
                ('registered_time', models.DateTimeField(auto_now_add=True, verbose_name='Время регистрации')),
                ('visited_time', models.DateTimeField(null=True, verbose_name='Время посещения')),
                ('refused_time', models.DateTimeField(null=True, verbose_name='Время отказа')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
