# Generated by Django 4.2.3 on 2023-08-04 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_guest_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания задачи')),
                ('progress_time', models.DateTimeField(verbose_name='Время взятия в работу')),
                ('closed_time', models.DateTimeField(verbose_name='Время завершения задачи')),
                ('cancel_time', models.DateTimeField(verbose_name='Время отмены задачи')),
                ('status', models.CharField(choices=[('NEW', 'Новая задача'), ('PROGRESS', 'Задача в работе'), ('CANCEL', 'Задача отменена'), ('CLOSED', 'Задача завершена')], verbose_name='Статус задачи')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_task_set', to='events.guest', verbose_name='Исполнитель задачи')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_task_set', to='events.guest')),
            ],
        ),
    ]
