# Generated by Django 4.2.4 on 2023-08-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_alter_task_executor_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('CANCEL', 'Задача отменена'), ('NEW', 'Новая задача'), ('PROGRESS', 'Задача в работе'), ('CLOSED', 'Задача завершена')], default='NEW', verbose_name='Статус задачи'),
        ),
    ]
