# Generated by Django 4.2.4 on 2023-08-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0043_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новая задача'), ('PROGRESS', 'Задача в работе'), ('CLOSED', 'Задача завершена'), ('CANCEL', 'Задача отменена')], default='NEW', verbose_name='Статус задачи'),
        ),
    ]
