# Generated by Django 4.2.4 on 2023-08-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0051_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='change_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
    ]
