# Generated by Django 4.2.4 on 2023-08-09 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0053_event_change_time_guest_change_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='change_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 3, 47, 14, 291187, tzinfo=datetime.timezone.utc), verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('CANCEL', 'Задача отменена'), ('PROGRESS', 'Задача в работе'), ('NEW', 'Новая задача'), ('CLOSED', 'Задача завершена')], default='NEW', verbose_name='Статус задачи'),
        ),
    ]
