# Generated by Django 4.2.4 on 2023-08-09 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0054_alter_event_change_time_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to='guests'),
        ),
        migrations.AlterField(
            model_name='event',
            name='change_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 7, 37, 42, 15773, tzinfo=datetime.timezone.utc), verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PROGRESS', 'Задача в работе'), ('CLOSED', 'Задача завершена'), ('CANCEL', 'Задача отменена'), ('NEW', 'Новая задача')], default='NEW', verbose_name='Статус задачи'),
        ),
    ]
